### ISSUE TITLE
new blockMeshDict

### ISSUE THREAD

**Issue by AndreWeiner** [AndreWeiner/naca0012_shock_buffet#1]
Hi @darshan315 
I have compiled some information to create the new blockMesh. Some general advice:
- you can start with the setup *test_cases/rhoCF_set1_alpha4_sa_g10000_ref1*
- the transition between blocks should be as smooth as possible
- the fewer tuning parameter the setup has, the better (e.g., you can try to make parameters depend on one another)
- if you get error messages about non-conformal faces, set the grading everywhere to one
- define all points, then build block after block, then add the arcs, and finally create the patches (trying to do all at once usually doesn't work)

Here is a sketch of the current blocking; there are two labels for each point - one for the upper and one for the lower surface.
![old_blocking](https://user-images.githubusercontent.com/8482575/129604315-71654a00-6d88-45cb-a607-e1fba24a38a6.jpg)

Here is my suggestion for the new blocking:
![blocking](https://user-images.githubusercontent.com/8482575/129604859-f7c1dd2b-fc9a-4976-b91d-058d9cb4efef.png)

Here is a snapshot of the mesh I've shown you today to give you an idea about grading and transitions:
![trailing_edge_mesh](https://user-images.githubusercontent.com/8482575/129604972-16d9b9ea-f195-4f29-b1b4-1cfd24150647.png)

If problems come up or more information is required, let me know.
Best, Andre

**Comment by darshan315** [comment]
Hello Andre,

I have made changes to [blockMeshDict](https://github.com/darshan315/naca0012_shock_buffet/blob/main/test_cases/rhoCF_set1_alpha4_sa_g10000_ref1/system/blockMeshDict). Please review it. While, I came across few problems.

-  I could not run the simulation due to [this](https://github.com/darshan315/naca0012_shock_buffet/blob/main/test_cases/rhoCF_set1_alpha4_sa_g10000_ref1/error.rhoCentralFoam) error. However, I am able to generate Meshing.
-  In meshing, while assigning different numbers of cells in _x_ and _y_ directions for a specific block, I am getting [this](https://github.com/darshan315/naca0012_shock_buffet/blob/main/test_cases/rhoCF_set1_alpha4_sa_g10000_ref1/error.blockMesh) error. I found [this](https://www.cfd-online.com/Forums/openfoam-meshing/230052-why-doesnt-simple-blockmesh-work-v2006.html) solution in the forum, however, I am not sure whether we should modify it.
- For the definition of vertices, I defined them based on my intuitions as I was not sure about the distance between them. Please let me know if changes are necessary. I have added the drawing(draw.io compatible) [here](https://github.com/darshan315/naca0012_shock_buffet/tree/main/test_cases/rhoCF_set1_alpha4_sa_g10000_ref1/Draw).
- For now, I have set all edgeGrading to 1 but I have tried changing it. I have a doubt regarding its value which we can discuss in our next meeting.

Best Regards,
Darshan Thummar.

**Comment by darshan315** [comment]
Hello Andre,
I have added the edge-grading and number of cells through the variables in the `domain()`. Please [check it](https://github.com/darshan315/naca0012_shock_buffet/blob/main/test_cases/rhoCF_set1_alpha4_sa_g10000_ref1/system/blockMeshDict) and let me know. (at the moment the mesh is on a coarse setting)
Best Regards,
Darshan Thummar.

**Comment by AndreWeiner** [comment]
Hi Darshan,
as mentioned yesterday, the mesh looks already quite good. Some small adjustments here and there and I'll be able to perform the first test run. Thanks!
Best, Andre
